#!/bin/bash
rm -rf vendor/codesleeve/stapler
composer $1
git apply workbench/benallfree/laravel-stapler-images/codesleeve-stapler-rename_bugfix.patch
git apply workbench/benallfree/laravel-stapler-images/codesleeve-stapler-curl-open-basedir-fix.patch
php artisan clear-compiled
php artisan optimize
find vendor -name '.git' | xargs rm -rf