<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Facebook\\' => array($vendorDir . '/facebook/php-sdk-v4/src/Facebook'),
    'Codesleeve\\Stapler\\' => array($vendorDir . '/codesleeve/stapler/src'),
    'Codesleeve\\LaravelStapler\\' => array($vendorDir . '/codesleeve/laravel-stapler/src'),
);
